services:
    _defaults:
        autowire: true
        autoconfigure: true

    Akyos\UxNativeCliBundle\:
        resource: '../src/'
        exclude:
            - '../src/AkyosUxNativeCliBundle.php'
